version: "3"

services:
  mongodb1:
    container_name: mongo1
    image: mongo
    restart: always
    volumes:
      - ./volumes/mongodb1:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"
    entrypoint:
      [
        "/usr/bin/mongod",
        "--port", "27017",
        "--replSet", "rs0",
        "--bind_ip_all",
      ]

  mongodb2:
    container_name: mongo2
    image: mongo
    restart: always
    volumes:
      - ./volumes/mongodb2:/data/db
    ports:
      - "27018:27018"
    expose:
      - "27018"
    entrypoint:
      [
        "/usr/bin/mongod",
        "--port", "27018",
        "--replSet", "rs0",
        "--bind_ip_all",
      ]

  mongodb3:
    container_name: mongo3
    image: mongo
    restart: always
    volumes:
      - ./volumes/mongodb3:/data/db
    ports:
      - "27019:27019"
    expose:
      - "27019"
    entrypoint:
      [
        "/usr/bin/mongod",
        "--port", "27019",
        "--replSet", "rs0",
        "--bind_ip_all",
      ]

  mongosetup:
    container_name: mongosetup
    image: "mongo-setup"
    build: "./"
    depends_on:
      - mongodb1

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb1:27017,mongodb2:27018,mongodb3:27019/?replicaSet=rs0
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - mongodb1
      - mongosetup
